[install]
state = enabled
is_configured = true

[ui]
is_visible = false

[launcher]
author = Splunk desde cero
description = Entradas y salida del Universal Forwarder
version = 1.0.0

[package]
id = mi_uf
